name = "rootrecord-api"
main = "src/rootrecord-api/worker.ts"
compatibility_date = "2024-11-01"
account_id = "d2daf26398a805b29e12ddba2b2228cf"

routes = [
  { pattern = "rootrecord.online/*", zone_name = "rootrecord.online" },
  { pattern = "api.rootrecord.online/*", zone_name = "rootrecord.online" },
]

[[d1_databases]]
binding = "AVA_HEARTBEAT_DB"
database_name = "ava-heartbeat"
database_id = "9991d162-a07f-4931-aa2f-2fbe6edc33c0"

[triggers]
crons = ["*/10 * * * *", "*/5 * * * *"]
